name:                logging-dhall
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/gbwey/logging-dhall#readme
license:             BSD3
copyright:           2018 Grant Weyburne
category:            Logging
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - dhall >= 1.32.0
  - template-haskell
  - text
  - unliftio-core
  - logging-simple

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wunused-type-patterns
  - -Wredundant-constraints
  when:
   - condition: impl(ghc >= 8.8)
     ghc-options:
     - -fwrite-ide-info
     - -hiedir=.hie
     - -Widentities

tests:
  logging-dhall-test:
    main:                Main.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    when:
       condition: impl(ghc >= 8.8)
       ghc-options:
       - -fwrite-ide-info
       - -hiedir=.hie
       - -Widentities
    dependencies:
    - base
    - logging-dhall
    - generic-lens
    - lens
    - tasty
    - tasty-hunit
